### PR TITLE
fix: add a DID parameter to UserList

### LINKED ISSUE #87: [Bug]: Bluesky followers of other accounts are just followers of the logged in account
As in the title, The UserDetailsScreen [does not pass](https://github.com/0xZhangKe/Fread/blob/4e5ff1cf1035e81ddfee64e28b78e423d1fa3bb6/plugins/bluesky/src/commonMain/kotlin/com/zhangke/fread/bluesky/internal/screen/user/detail/BskyUserDetailScreen.kt#L101-L106) any information to the UserListScreen to specify which user's followers / following is to be displayed thus the UserListScreen always [assumes](https://github.com/0xZhangKe/Fread/blob/4e5ff1cf1035e81ddfee64e28b78e423d1fa3bb6/plugins/bluesky/src/commonMain/kotlin/com/zhangke/fread/bluesky/internal/screen/user/list/UserListViewModel.kt#L209-L224) it's the followers/following of the loggedinuser.

### PR DESCRIPTION
**Pull request by realstealthninja**
This pr adds a parameter for the UserList so that each instance is specific to the given user did.

fixes #87

### CODE REVIEW

File: plugins/bluesky/src/commonMain/kotlin/com/zhangke/fread/bluesky/internal/screen/user/list/UserListScreen.kt [hunk 1]
```diff
@@ -72,7 +73,7 @@ class UserListScreen(
             onUnmuteClick = viewModel::onUnmuteClick,
             onBlockClick = viewModel::onBlockClick,
             onUnblockClick = viewModel::onUnblockClick,
-            onUserClick = { navigator.push(BskyUserDetailScreen(locator, it.did)) },
+            onUserClick = fun(item: UserListItemUiState): Unit {navigator.push(BskyUserDetailScreen(locator, item.did))},
```
Comment (0xZhangKe) [inline plugins/bluesky/src/commonMain/kotlin/com/zhangke/fread/bluesky/internal/screen/user/list/UserListScreen.kt]: The syntax here seems a bit odd. I think you could directly use a lambda expression, for example: 
`onUserClick = {navigator.push(BskyUserDetailScreen(locator, it.did))}`.

**Comment by realstealthninja** [comment]
> It seems that in Fread, when a user opens another user's Follower page, the displayed follower list is always the currently logged-in account?

yes! its always my followers or my following when click on other's followers

File: plugins/bluesky/src/commonMain/kotlin/com/zhangke/fread/bluesky/internal/screen/user/list/UserListScreen.kt (hunk 1 above)
Comment (realstealthninja) [reply plugins/bluesky/src/commonMain/kotlin/com/zhangke/fread/bluesky/internal/screen/user/list/UserListScreen.kt]: Remnants of some tests i did, will fix it shortly.
